# Generated by Django 5.1.3 on 2024-11-16 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scooters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Иконка')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=1, verbose_name='Цена')),
                ('time', models.IntegerField(default=1, verbose_name='Купленное время')),
                ('buy_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('scooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scooters.scooter', verbose_name='Самокат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
    ]
