# Generated by Django 5.1.3 on 2024-11-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Изображение')),
                ('price', models.IntegerField(default=1, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Самокат',
                'verbose_name_plural': 'Самокаты',
            },
        ),
    ]
